export const monsterTemplates = [
    {
        species: "Lamball",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "001",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Cattiva ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "002",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Cool Cattiva ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "002A",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Lucky Cattiva ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "002A1",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Spooky Cattiva ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "002A2",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Chikipi ",
        hp: 60,
        attack: 60,
        defense: 60,
        speed: 10,
	paldeck: "003",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Lifmunk ",
        hp: 75,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "004",
	type1: "Grass",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Fuack ",
        hp: 60,
        attack: 80,
        defense: 60,
        speed: 10,
	paldeck: "005",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Fuack Ignis ",
        hp: 60,
        attack: 85,
        defense: 60,
        speed: 10,
	paldeck: "005B",
	type1: "Water",
	type2: "Fire",
        rarity: "Common"
    },
    {
        species: "Vixy ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "006",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Celaray ",
        hp: 80,
        attack: 70,
        defense: 80,
        speed: 10,
	paldeck: "007",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Celaray Lux ",
        hp: 80,
        attack: 75,
        defense: 80,
        speed: 10,
	paldeck: "007B",
	type1: "Water",
	type2: "Electric",
        rarity: "Common"
    },
    {
        species: "Cremis ",
        hp: 70,
        attack: 70,
        defense: 75,
        speed: 10,
	paldeck: "008",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Croajiro ",
        hp: 80,
        attack: 100,
        defense: 85,
        speed: 10,
	paldeck: "009",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Croajiro Noct ",
        hp: 85,
        attack: 110,
        defense: 90,
        speed: 10,
	paldeck: "009B",
	type1: "Water",
	type2: "Dark",
        rarity: "Common"
    },
    {
        species: "Witch Croajiro ",
        hp: 80,
        attack: 100,
        defense: 85,
        speed: 10,
	paldeck: "009A",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Herbil ",
        hp: 80,
        attack: 75,
        defense: 75,
        speed: 10,
	paldeck: "010",
	type1: "Neutral",
	type2: "Grass",
        rarity: "Common"
    },
    {
        species: "Teafant ",
        hp: 70,
        attack: 60,
        defense: 70,
        speed: 10,
	paldeck: "011",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Gumoss ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "012",
	type1: "Grass",
	type2: "Ground",
        rarity: "Common"
    },
    {
        species: "Pudding Gumoss ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "012A",
	type1: "Grass",
	type2: "Ground",
        rarity: "Common"
    },
    {
        species: "Pupperai ",
        hp: 70,
        attack: 80,
        defense: 70,
        speed: 10,
	paldeck: "013",
	type1: "Ground",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Clovee ",
        hp: 80,
        attack: 65,
        defense: 65,
        speed: 10,
	paldeck: "014",
	type1: "Grass",
	type2: "Neutral",
        rarity: "Common"
    },
    {
        species: "Jolthog ",
        hp: 70,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "015",
	type1: "Electric",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Jolthog Cryst ",
        hp: 70,
        attack: 75,
        defense: 80,
        speed: 10,
	paldeck: "015B",
	type1: "Ice",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Depresso ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "016",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Party Night Depresso ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "016A",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Pengullet ",
        hp: 70,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "017",
	type1: "Water",
	type2: "Ice",
        rarity: "Common"
    },
    {
        species: "Pengullet Lux",
        hp: 70,
        attack: 80,
        defense: 70,
        speed: 10,
	paldeck: "017B",
	type1: "Water",
	type2: "Electric",
        rarity: "Common"
    },
    {
        species: "Pirate Pengullet ",
        hp: 70,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "017A",
	type1: "Water",
	type2: "Ice",
        rarity: "Common"
    },
    {
        species: "Penking ",
        hp: 95,
        attack: 95,
        defense: 95,
        speed: 10,
	paldeck: "018",
	type1: "Water",
	type2: "Ice",
        rarity: "Rare"
    },
    {
        species: "Penking Lux",
        hp: 100,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "018B",
	type1: "Water",
	type2: "Electric",
        rarity: "Rare"
    },
    {
        species: "Hoocrates ",
        hp: 70,
        attack: 70,
        defense: 80,
        speed: 10,
	paldeck: "019",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Melpaca ",
        hp: 90,
        attack: 75,
        defense: 90,
        speed: 10,
	paldeck: "020",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Kingpaca ",
        hp: 120,
        attack: 85,
        defense: 90,
        speed: 10,
	paldeck: "021",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Kingpaca Cryst ",
        hp: 120,
        attack: 85,
        defense: 90,
        speed: 10,
	paldeck: "021B",
	type1: "Ice",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Daedream ",
        hp: 70,
        attack: 75,
        defense: 60,
        speed: 10,
	paldeck: "022",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Tanzee ",
        hp: 80,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "023",
	type1: "Grass",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Tanzee Ignis",
        hp: 80,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "023B",
	type1: "Fire",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Nox ",
        hp: 75,
        attack: 85,
        defense: 70,
        speed: 10,
	paldeck: "024",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Flambelle ",
        hp: 60,
        attack: 70,
        defense: 80,
        speed: 10,
	paldeck: "025",
	type1: "Fire",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Rooby ",
        hp: 75,
        attack: 70,
        defense: 75,
        speed: 10,
	paldeck: "026",
	type1: "Fire",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Mau ",
        hp: 70,
        attack: 60,
        defense: 70,
        speed: 10,
	paldeck: "027",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Mau Cryst ",
        hp: 70,
        attack: 65,
        defense: 70,
        speed: 10,
	paldeck: "027B",
	type1: "Ice",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Rushroar ",
        hp: 80,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "028",
	type1: "Ground",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Foxparks ",
        hp: 65,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "029",
	type1: "Fire",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Foxparks Cryst ",
        hp: 65,
        attack: 80,
        defense: 70,
        speed: 10,
	paldeck: "029B",
	type1: "Ice",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Killamari ",
        hp: 60,
        attack: 60,
        defense: 70,
        speed: 10,
	paldeck: "030",
	type1: "Dark",
	type2: "Water",
        rarity: "Rare"
    },
    {
        species: "Killamari Primo",
        hp: 70,
        attack: 60,
        defense: 70,
        speed: 10,
	paldeck: "030B",
	type1: "Neutral",
	type2: "Water",
        rarity: "Rare"
    },
    {
        species: "Fuddler ",
        hp: 65,
        attack: 80,
        defense: 50,
        speed: 10,
	paldeck: "031",
	type1: "Ground",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Eikthyrdeer ",
        hp: 95,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "032",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Eikthyrdeer Terra",
        hp: 95,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "032",
	type1: "Ground",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Direhowl ",
        hp: 80,
        attack: 90,
        defense: 75,
        speed: 10,
	paldeck: "033",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Caprity ",
        hp: 100,
        attack: 70,
        defense: 90,
        speed: 10,
	paldeck: "034",
	type1: "Grass",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Caprity Noct",
        hp: 100,
        attack: 75,
        defense: 90,
        speed: 10,
	paldeck: "034B",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Swee ",
        hp: 60,
        attack: 60,
        defense: 60,
        speed: 10,
	paldeck: "035",
	type1: "Ice",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Sweepa ",
        hp: 100,
        attack: 90,
        defense: 90,
        speed: 10,
	paldeck: "036",
	type1: "Ice",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Turtacle ",
        hp: 75,
        attack: 75,
        defense: 115,
        speed: 10,
	paldeck: "037",
	type1: "Water",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Turtacle Terra",
        hp: 85,
        attack: 85,
        defense: 125,
        speed: 10,
	paldeck: "037B",
	type1: "Water",
	type2: "Ground",
        rarity: "Rare"
    },
    {
        species: "Hangyu ",
        hp: 80,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "038",
	type1: "Ground",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Hangyu Cryst",
        hp: 80,
        attack: 80,
        defense: 70,
        speed: 10,
	paldeck: "038B",
	type1: "Ice",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Woolipop ",
        hp: 70,
        attack: 70,
        defense: 90,
        speed: 10,
	paldeck: "039",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Woolipop Terra ",
        hp: 70,
        attack: 70,
        defense: 95,
        speed: 10,
	paldeck: "039B",
	type1: "Ground",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Mozzarina ",
        hp: 90,
        attack: 50,
        defense: 80,
        speed: 10,
	paldeck: "040",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Azurobe ",
        hp: 110,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "041",
	type1: "Water",
	type2: "Dragon",
        rarity: "Rare"
    },
    {
        species: "Azurobe Cryst",
        hp: 115,
        attack: 105,
        defense: 105,
        speed: 10,
	paldeck: "041B",
	type1: "Ice",
	type2: "Dragon",
        rarity: "Rare"
    },
    {
        species: "Sparkit ",
        hp: 60,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "042",
	type1: "Electric",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Kelpsea ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "043",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Kelpsea Ignis",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "043B",
	type1: "Fire",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Ribunny ",
        hp: 75,
        attack: 65,
        defense: 70,
        speed: 10,
	paldeck: "044",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Ribunny Botan ",
        hp: 80,
        attack: 65,
        defense: 70,
        speed: 10,
	paldeck: "044B",
	type1: "Grass",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Jelliette ",
        hp: 75,
        attack: 90,
        defense: 70,
        speed: 10,
	paldeck: "045",
	type1: "Water",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Jellroy ",
        hp: 90,
        attack: 75,
        defense: 75,
        speed: 10,
	paldeck: "046",
	type1: "Water",
	type2: "Dark",
        rarity: "Rare"
    },
    {
        species: "Amione ",
        hp: 65,
        attack: 70,
        defense: 65,
        speed: 10,
	paldeck: "047",
	type1: "Water",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Gloopie ",
        hp: 70,
        attack: 85,
        defense: 70,
        speed: 10,
	paldeck: "048",
	type1: "Water",
	type2: "Dark",
        rarity: "Epic"
    },
    {
        species: "Gloopie Primo",
        hp: 70,
        attack: 85,
        defense: 70,
        speed: 10,
	paldeck: "048B",
	type1: "Water",
	type2: "Neutral",
        rarity: "Epic"
    },
    {
        species: "Galeclaw ",
        hp: 75,
        attack: 85,
        defense: 60,
        speed: 10,
	paldeck: "049",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Wispaw ",
        hp: 85,
        attack: 95,
        defense: 70,
        speed: 10,
	paldeck: "050",
	type1: "Dark",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Nitewing ",
        hp: 100,
        attack: 95,
        defense: 80,
        speed: 10,
	paldeck: "051",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Tombat ",
        hp: 95,
        attack: 95,
        defense: 80,
        speed: 10,
	paldeck: "052",
	type1: "Dark",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Tocotoco ",
        hp: 60,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "053",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Univolt ",
        hp: 80,
        attack: 105,
        defense: 105,
        speed: 10,
	paldeck: "054",
	type1: "Electric",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Univolt Cryst ",
        hp: 80,
        attack: 105,
        defense: 110,
        speed: 10,
	paldeck: "054B",
	type1: "Ice",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Gobfin ",
        hp: 90,
        attack: 90,
        defense: 75,
        speed: 10,
	paldeck: "055",
	type1: "Water",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Gobfin Ignis",
        hp: 90,
        attack: 90,
        defense: 75,
        speed: 10,
	paldeck: "055B",
	type1: "Fire",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Loupmoon ",
        hp: 80,
        attack: 100,
        defense: 80,
        speed: 10,
	paldeck: "056",
	type1: "Dark",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Loupmoon Cryst ",
        hp: 80,
        attack: 105,
        defense: 80,
        speed: 10,
	paldeck: "056B",
	type1: "Ice",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Cawgnito ",
        hp: 75,
        attack: 95,
        defense: 80,
        speed: 10,
	paldeck: "057",
	type1: "Dark",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Arsox ",
        hp: 85,
        attack: 95,
        defense: 95,
        speed: 10,
	paldeck: "058",
	type1: "Fire",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Muffly ",
        hp: 60,
        attack: 80,
        defense: 55,
        speed: 10,
	paldeck: "059",
	type1: "Ice",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Bristla ",
        hp: 80,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "060",
	type1: "Grass",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Cinnamoth ",
        hp: 70,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "061",
	type1: "Grass",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Puffolt ",
        hp: 75,
        attack: 80,
        defense: 70,
        speed: 10,
	paldeck: "062",
	type1: "Electric",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Elphidran ",
        hp: 110,
        attack: 80,
        defense: 90,
        speed: 10,
	paldeck: "063",
	type1: "Dragon",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Elphidran Aqua ",
        hp: 115,
        attack: 80,
        defense: 95,
        speed: 10,
	paldeck: "063B",
	type1: "Dragon",
	type2: "Water",
        rarity: "Epic"
    },
    {
        species: "Vanwyrm ",
        hp: 90,
        attack: 115,
        defense: 90,
        speed: 10,
	paldeck: "064",
	type1: "Fire",
	type2: "Dark",
        rarity: "Rare"
    },
    {
        species: "Vanwyrm Cryst",
        hp: 90,
        attack: 120,
        defense: 95,
        speed: 10,
	paldeck: "064B",
	type1: "Ice",
	type2: "Dark",
        rarity: "Rare"
    },
    {
        species: "Felbat ",
        hp: 100,
        attack: 105,
        defense: 110,
        speed: 10,
	paldeck: "065",
	type1: "Dark",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Vaelet ",
        hp: 100,
        attack: 100,
        defense: 120,
        speed: 10,
	paldeck: "066",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Beegarde ",
        hp: 80,
        attack: 90,
        defense: 90,
        speed: 10,
	paldeck: "067",
	type1: "Grass",
	type2: "",
        rarity: "Rarw"
    },
    {
        species: "Elizabee ",
        hp: 90,
        attack: 105,
        defense: 100,
        speed: 10,
	paldeck: "068",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Lovander ",
        hp: 120,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "069",
	type1: "Dark",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Grintale ",
        hp: 110,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "070",
	type1: "Neutal",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Tarantiss ",
        hp: 110,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "071",
	type1: "Dark",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Polapup ",
        hp: 95,
        attack: 105,
        defense: 105,
        speed: 10,
	paldeck: "072",
	type1: "Ice",
	type2: "Water",
        rarity: "Rare"
    },
    {
        species: "Polapup Terra",
        hp: 95,
        attack: 105,
        defense: 110,
        speed: 10,
	paldeck: "072B",
	type1: "Ice",
	type2: "Ground",
        rarity: "Rare"
    },
    {
        species: "Leezpunk ",
        hp: 80,
        attack: 80,
        defense: 50,
        speed: 10,
	paldeck: "073",
	type1: "Dark",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Leezpunk Ignis",
        hp: 80,
        attack: 80,
        defense: 50,
        speed: 10,
	paldeck: "073B",
	type1: "Fire",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Gorirat ",
        hp: 90,
        attack: 95,
        defense: 90,
        speed: 10,
	paldeck: "074",
	type1: "Neutral",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Gorirat Terra",
        hp: 90,
        attack: 100,
        defense: 90,
        speed: 10,
	paldeck: "074B",
	type1: "Ground",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Surfent ",
        hp: 90,
        attack: 90,
        defense: 80,
        speed: 10,
	paldeck: "075",
	type1: "Water",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Surfent Terra",
        hp: 90,
        attack: 90,
        defense: 100,
        speed: 10,
	paldeck: "075B",
	type1: "Ground",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Robinquill ",
        hp: 90,
        attack: 105,
        defense: 80,
        speed: 10,
	paldeck: "076",
	type1: "Grass",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Robinquill Terra ",
        hp: 90,
        attack: 105,
        defense: 80,
        speed: 10,
	paldeck: "076B",
	type1: "Grass",
	type2: "Ground",
        rarity: "Legendary"
    },
    {
        species: "Flopie ",
        hp: 75,
        attack: 65,
        defense: 70,
        speed: 10,
	paldeck: "077",
	type1: "Grass",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Wixen ",
        hp: 90,
        attack: 110,
        defense: 80,
        speed: 10,
	paldeck: "078",
	type1: "Fire",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Wixen Noct",
        hp: 90,
        attack: 110,
        defense: 85,
        speed: 10,
	paldeck: "078B",
	type1: "Fire",
	type2: "Dark",
        rarity: "Epic"
    },

    {
        species: "Katress ",
        hp: 90,
        attack: 105,
        defense: 90,
        speed: 10,
	paldeck: "079",
	type1: "Dark",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Katress Ignis",
        hp: 95,
        attack: 105,
        defense: 90,
        speed: 10,
	paldeck: "079B",
	type1: "Dark",
	type2: "Fire",
        rarity: "Epic"
    },
    {
        species: "Spectacled Katress ",
        hp: 90,
        attack: 105,
        defense: 90,
        speed: 10,
	paldeck: "079A",
	type1: "Dark",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Helzephyr ",
        hp: 100,
        attack: 125,
        defense: 100,
        speed: 10,
	paldeck: "080",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Helzephyr Lux",
        hp: 105,
        attack: 125,
        defense: 100,
        speed: 10,
	paldeck: "080B",
	type1: "Dark",
	type2: "Electric",
        rarity: "Legendary"
    },
    {
        species: "Elgrove ",
        hp: 110,
        attack: 105,
        defense: 105,
        speed: 10,
	paldeck: "081",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Elgrove Cryst",
        hp: 120,
        attack: 100,
        defense: 105,
        speed: 10,
	paldeck: "081B",
	type1: "Ice",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Lunaris ",
        hp: 90,
        attack: 100,
        defense: 90,
        speed: 10,
	paldeck: "082",
	type1: "Neutral",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Fenglope ",
        hp: 110,
        attack: 110,
        defense: 90,
        speed: 10,
	paldeck: "083",
	type1: "Neutral",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Fenglope Lux",
        hp: 110,
        attack: 115,
        defense: 90,
        speed: 10,
	paldeck: "083B",
	type1: "Electric",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Dinossom ",
        hp: 110,
        attack: 85,
        defense: 90,
        speed: 10,
	paldeck: "084",
	type1: "Grass",
	type2: "Dragon",
        rarity: "Legendary"
    },
    {
        species: "Dinossom Lux",
        hp: 110,
        attack: 90,
        defense: 90,
        speed: 10,
	paldeck: "084B",
	type1: "Electric",
	type2: "Dragon",
        rarity: "Legendary"
    },
    {
        species: "Bushi ",
        hp: 80,
        attack: 125,
        defense: 80,
        speed: 10,
	paldeck: "085",
	type1: "Fire",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Bushi Noct",
        hp: 80,
        attack: 130,
        defense: 80,
        speed: 10,
	paldeck: "085B",
	type1: "Fire",
	type2: "Dark",
        rarity: "Epic"
    },
    {
        species: "Munchill ",
        hp: 75,
        attack: 80,
        defense: 85,
        speed: 10,
	paldeck: "086",
	type1: "Water",
	type2: "Ice",
        rarity: "Epic"
    },
    {
        species: "Mammorest ",
        hp: 150,
        attack: 85,
        defense: 90,
        speed: 10,
	paldeck: "087",
	type1: "Grass",
	type2: "Ground",
        rarity: "Rare"
    },
    {
        species: "Mammorest Cryst",
        hp: 150,
        attack: 85,
        defense: 90,
        speed: 10,
	paldeck: "087B",
	type1: "Ice",
	type2: "Ground",
        rarity: "Rare"
    },
    {
        species: "Finsider ",
        hp: 75,
        attack: 85,
        defense: 80,
        speed: 10,
	paldeck: "088",
	type1: "Water",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Finsider Ignis ",
        hp: 75,
        attack: 90,
        defense: 80,
        speed: 10,
	paldeck: "088B",
	type1: "Water",
	type2: "Fire",
        rarity: "Rare"
    },

    {
        species: "Petallia ",
        hp: 100,
        attack: 95,
        defense: 100,
        speed: 10,
	paldeck: "089",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Petallia Ignis ",
        hp: 95,
        attack: 105,
        defense: 100,
        speed: 10,
	paldeck: "089B",
	type1: "Grass",
	type2: "Fire",
        rarity: "Epic"
    },
    {
        species: "Leafan ",
        hp: 100,
        attack: 115,
        defense: 95,
        speed: 10,
	paldeck: "090",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Incineram ",
        hp: 95,
        attack: 100,
        defense: 85,
        speed: 10,
	paldeck: "091",
	type1: "Fire",
	type2: "Dark",
        rarity: "Epic"
    },
    {
        species: "Incineram Noct",
        hp: 95,
        attack: 105,
        defense: 85,
        speed: 10,
	paldeck: "091B",
	type1: "Dark",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Dazzi ",
        hp: 70,
        attack: 80,
        defense: 70,
        speed: 10,
	paldeck: "092",
	type1: "Electric",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Dazzi Noct",
        hp: 70,
        attack: 80,
        defense: 75,
        speed: 10,
	paldeck: "092B",
	type1: "Dark",
	type2: "Electric",
        rarity: "Epic"
    },
    {
        species: "Pyrin ",
        hp: 100,
        attack: 95,
        defense: 90,
        speed: 10,
	paldeck: "093",
	type1: "Fire",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Pyrin Noct",
        hp: 100,
        attack: 95,
        defense: 90,
        speed: 10,
	paldeck: "093B",
	type1: "Fire",
	type2: "Dark",
        rarity: "Epic"
    },
    {
        species: "Relaxaurus ",
        hp: 120,
        attack: 115,
        defense: 110,
        speed: 10,
	paldeck: "094",
	type1: "Dragon",
	type2: "Water",
        rarity: "Epic"
    },
    {
        species: "Relaxaurus Lux ",
        hp: 120,
        attack: 120,
        defense: 110,
        speed: 10,
	paldeck: "094B",
	type1: "Dragon",
	type2: "Electric",
        rarity: "Epic"
    },
    {
        species: "Golden Relaxaurus ",
        hp: 120,
        attack: 115,
        defense: 110,
        speed: 10,
	paldeck: "094A",
	type1: "Dragon",
	type2: "Water",
        rarity: "Epic"
    },
    {
        species: "Foxcicle ",
        hp: 90,
        attack: 95,
        defense: 105,
        speed: 10,
	paldeck: "095",
	type1: "Ice",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Beakon ",
        hp: 105,
        attack: 115,
        defense: 80,
        speed: 10,
	paldeck: "096",
	type1: "Electric",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Beakon Cryst",
        hp: 105,
        attack: 115,
        defense: 85,
        speed: 10,
	paldeck: "096B",
	type1: "Ice",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Ghangler ",
        hp: 90,
        attack: 125,
        defense: 105,
        speed: 10,
	paldeck: "097",
	type1: "Dark",
	type2: "Water",
        rarity: "Epic"
    },
    {
        species: "Ghangler Ignis",
        hp: 90,
        attack: 130,
        defense: 105,
        speed: 10,
	paldeck: "097B",
	type1: "Dark",
	type2: "Fire",
        rarity: "Epic"
    },
    {
        species: "Rayhound ",
        hp: 90,
        attack: 100,
        defense: 80,
        speed: 10,
	paldeck: "098",
	type1: "Electric",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Rayhound Cryst",
        hp: 90,
        attack: 105,
        defense: 80,
        speed: 10,
	paldeck: "098B",
	type1: "Ice",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Menasting ",
        hp: 100,
        attack: 100,
        defense: 130,
        speed: 10,
	paldeck: "099",
	type1: "Dark",
	type2: "Ground",
        rarity: "Epic"
    },
    {
        species: "Menasting Terra",
        hp: 100,
        attack: 100,
        defense: 130,
        speed: 10,
	paldeck: "099B",
	type1: "Ground",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Needoll ",
        hp: 75,
        attack: 85,
        defense: 70,
        speed: 10,
	paldeck: "100",
	type1: "Grass",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Needoll Noct",
        hp: 75,
        attack: 90,
        defense: 70,
        speed: 10,
	paldeck: "100B",
	type1: "Grass",
	type2: "Dark",
        rarity: "Rare"
    },
    {
        species: "Reindrix ",
        hp: 100,
        attack: 85,
        defense: 110,
        speed: 10,
	paldeck: "101",
	type1: "Ice",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Mossanda ",
        hp: 100,
        attack: 90,
        defense: 90,
        speed: 10,
	paldeck: "102",
	type1: "Grass",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Mossanda Lux",
        hp: 100,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "102B",
	type1: "Electric",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Chillet ",
        hp: 90,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "103",
	type1: "Ice",
	type2: "Dragon",
        rarity: "Epic"
    },
    {
        species: "Snorkle Chillet ",
        hp: 90,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "103A",
	type1: "Ice",
	type2: "Dragon",
        rarity: "Epic"
    },
    {
        species: "Crown Chillet ",
        hp: 90,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "103A1",
	type1: "Ice",
	type2: "Dragon",
        rarity: "Epic"
    },
    {
        species: "Winter Chillet ",
        hp: 90,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "103A2",
	type1: "Ice",
	type2: "Dragon",
        rarity: "Epic"
    },
    {
        species: "Lion Dancer Chillet ",
        hp: 90,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "103A3",
	type1: "Ice",
	type2: "Dragon",
        rarity: "Epic"
    },
    {
        species: "Chillet Ignis ",
        hp: 90,
        attack: 85,
        defense: 80,
        speed: 10,
	paldeck: "103B",
	type1: "Fire",
	type2: "Dragon",
        rarity: "Epic"
    },
    {
        species: "Lion Dancer Chillet Ignis ",
        hp: 90,
        attack: 85,
        defense: 80,
        speed: 10,
	paldeck: "103B1",
	type1: "Fire",
	type2: "Dragon",
        rarity: "Epic"
    },
    {
        species: "Winter Chillet Ignis ",
        hp: 90,
        attack: 85,
        defense: 80,
        speed: 10,
	paldeck: "103B2",
	type1: "Fire",
	type2: "Dragon",
        rarity: "Epic"
    },
    {
        species: "Ragnahawk ",
        hp: 95,
        attack: 105,
        defense: 120,
        speed: 10,
	paldeck: "104",
	type1: "Fire",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Moldron ",
        hp: 110,
        attack: 125,
        defense: 115,
        speed: 10,
	paldeck: "105",
	type1: "Fire",
	type2: "Ground",
        rarity: "Epic"
    },
    {
        species: "Moldron Cryst",
        hp: 110,
        attack: 125,
        defense: 120,
        speed: 10,
	paldeck: "105B",
	type1: "Ice",
	type2: "Ground",
        rarity: "Epic"
    },
    {
        species: "Palumba ",
        hp: 105,
        attack: 110,
        defense: 115,
        speed: 10,
	paldeck: "106",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Digtoise ",
        hp: 110,
        attack: 125,
        defense: 115,
        speed: 10,
	paldeck: "107",
	type1: "Ground",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Broncherry ",
        hp: 120,
        attack: 90,
        defense: 100,
        speed: 10,
	paldeck: "108",
	type1: "Grass",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Broncherry Aqua",
        hp: 120,
        attack: 95,
        defense: 100,
        speed: 10,
	paldeck: "108B",
	type1: "Grass",
	type2: "Water",
        rarity: "Rare"
    },
    {
        species: "Dumud ",
        hp: 100,
        attack: 70,
        defense: 95,
        speed: 10,
	paldeck: "109",
	type1: "Ground",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Dumud Gild",
        hp: 105,
        attack: 75,
        defense: 100,
        speed: 10,
	paldeck: "109B",
	type1: "Ground",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Brahola ",
        hp: 130,
        attack: 95,
        defense: 120,
        speed: 10,
	paldeck: "110",
	type1: "Grass",
	type2: "Ground",
        rarity: "Rare"
    },
    {
        species: "Kitsun ",
        hp: 100,
        attack: 115,
        defense: 100,
        speed: 10,
	paldeck: "111",
	type1: "Fire",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Kitsun Noct",
        hp: 100,
        attack: 115,
        defense: 105,
        speed: 10,
	paldeck: "111B",
	type1: "Dark",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Blazehowl ",
        hp: 105,
        attack: 110,
        defense: 80,
        speed: 10,
	paldeck: "112",
	type1: "Fire",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Blazehowl Noct",
        hp: 105,
        attack: 115,
        defense: 80,
        speed: 10,
	paldeck: "112B",
	type1: "Fire",
	type2: "Dark",
        rarity: "Rare"
    },
    {
        species: "Warsect ",
        hp: 120,
        attack: 100,
        defense: 120,
        speed: 10,
	paldeck: "113",
	type1: "Ground",
	type2: "Grass",
        rarity: "Legendary"
    },
    {
        species: "Warsect Terra",
        hp: 120,
        attack: 105,
        defense: 120,
        speed: 10,
	paldeck: "113B",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Frostplume ",
        hp: 110,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "114",
	type1: "Ice",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Majex ",
        hp: 110,
        attack: 115,
        defense: 90,
        speed: 10,
	paldeck: "115",
	type1: "Dark",
	type2: "Fire",
        rarity: "Epic"
    },
    {
        species: "Sibelyx ",
        hp: 110,
        attack: 90,
        defense: 100,
        speed: 10,
	paldeck: "116",
	type1: "Ice",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Sibelyx Primo",
        hp: 115,
        attack: 90,
        defense: 100,
        speed: 10,
	paldeck: "116B",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Maraith ",
        hp: 75,
        attack: 105,
        defense: 80,
        speed: 10,
	paldeck: "117",
	type1: "Dark",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Shroomer ",
        hp: 110,
        attack: 80,
        defense: 90,
        speed: 10,
	paldeck: "118",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Shroomer Noct",
        hp: 110,
        attack: 85,
        defense: 90,
        speed: 10,
	paldeck: "118B",
	type1: "Grass",
	type2: "Dark",
        rarity: "Epic"
    },
    {
        species: "Icelyn ",
        hp: 95,
        attack: 115,
        defense: 105,
        speed: 10,
	paldeck: "119",
	type1: "Ice",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Gildra ",
        hp: 105,
        attack: 120,
        defense: 105,
        speed: 10,
	paldeck: "120",
	type1: "Dark",
	type2: "Ground",
        rarity: "Legendary"
    },
    {
        species: "Jormuntide ",
        hp: 130,
        attack: 120,
        defense: 100,
        speed: 10,
	paldeck: "121",
	type1: "Dragon",
	type2: "Water",
        rarity: "Epic"
    },
    {
        species: "Jormuntide Ignis",
        hp: 130,
        attack: 130,
        defense: 100,
        speed: 10,
	paldeck: "121B",
	type1: "Dragon",
	type2: "Fire",
        rarity: "Legendary"
    },
    {
        species: "Suzaku ",
        hp: 120,
        attack: 105,
        defense: 105,
        speed: 10,
	paldeck: "122",
	type1: "Fire",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Suzaku Aqua",
        hp: 125,
        attack: 105,
        defense: 105,
        speed: 10,
	paldeck: "122B",
	type1: "Water",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Dazemu ",
        hp: 95,
        attack: 90,
        defense: 80,
        speed: 10,
	paldeck: "123",
	type1: "Ground",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Quivern ",
        hp: 105,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "124",
	type1: "Dragon",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Sailor Quivern ",
        hp: 105,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "124A",
	type1: "Dragon",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Quivern Botan",
        hp: 105,
        attack: 105,
        defense: 100,
        speed: 10,
	paldeck: "124B",
	type1: "Dragon",
	type2: "Grass",
        rarity: "Legendary"
    },
    {
        species: "Lullu",
        hp: 90,
        attack: 90,
        defense: 80,
        speed: 10,
	paldeck: "125",
	type1: "Grass",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Kikit",
        hp: 75,
        attack: 70,
        defense: 90,
        speed: 10,
	paldeck: "126",
	type1: "Ground",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Yakumo",
        hp: 85,
        attack: 85,
        defense: 85,
        speed: 10,
	paldeck: "127",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Skutlass",
        hp: 70,
        attack: 100,
        defense: 80,
        speed: 10,
	paldeck: "128",
	type1: "Water",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Skutlass Ignis",
        hp: 70,
        attack: 105,
        defense: 80,
        speed: 10,
	paldeck: "128B",
	type1: "Water",
	type2: "Fire",
        rarity: "Legendary"
    },
    {
        species: "Reptyro",
        hp: 110,
        attack: 105,
        defense: 120,
        speed: 10,
	paldeck: "129",
	type1: "Fire",
	type2: "Ground",
        rarity: "Legendary"
    },
    {
        species: "Reptyro Cryst",
        hp: 110,
        attack: 105,
        defense: 130,
        speed: 10,
	paldeck: "129B",
	type1: "Ice",
	type2: "Ground",
        rarity: "Legendary"
    },
    {
        species: "Starryon",
        hp: 110,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "130",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Starryon Primo",
        hp: 110,
        attack: 105,
        defense: 100,
        speed: 10,
	paldeck: "130B",
	type1: "Neutral",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Pierdon",
        hp: 100,
        attack: 105,
        defense: 120,
        speed: 10,
	paldeck: "131",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Pierdon",
        hp: 100,
        attack: 105,
        defense: 120,
        speed: 10,
	paldeck: "131",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Pierdon Cryst",
        hp: 100,
        attack: 110,
        defense: 120,
        speed: 10,
	paldeck: "131B",
	type1: "Ice",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Cryolinx",
        hp: 100,
        attack: 105,
        defense: 110,
        speed: 10,
	paldeck: "132",
	type1: "Ice",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Cryolinx Terra",
        hp: 100,
        attack: 105,
        defense: 110,
        speed: 10,
	paldeck: "132B",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Snugloo",
        hp: 80,
        attack: 75,
        defense: 85,
        speed: 10,
	paldeck: "133",
	type1: "Ice",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Wumpo",
        hp: 140,
        attack: 80,
        defense: 100,
        speed: 10,
	paldeck: "134",
	type1: "Ice",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Wumpo Botan",
        hp: 140,
        attack: 80,
        defense: 110,
        speed: 10,
	paldeck: "134B",
	type1: "Grass",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Sootseer",
        hp: 105,
        attack: 125,
        defense: 90,
        speed: 10,
	paldeck: "135",
	type1: "Dark",
	type2: "Fire",
        rarity: "Legendary"
    },
    {
        species: "Carnibora",
        hp: 85,
        attack: 90,
        defense: 85,
        speed: 10,
	paldeck: "136",
	type1: "Grass",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Blazamut",
        hp: 100,
        attack: 125,
        defense: 120,
        speed: 10,
	paldeck: "137",
	type1: "Fire",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Blazamut Ryu",
        hp: 105,
        attack: 130,
        defense: 125,
        speed: 10,
	paldeck: "137B",
	type1: "Fire",
	type2: "Dark",
        rarity: "Legendary"
    },
    {
        species: "Dualith",
        hp: 110,
        attack: 105,
        defense: 125,
        speed: 10,
	paldeck: "138",
	type1: "Ground",
	type2: "Grass",
        rarity: "Legendary"
    },
    {
        species: "Dualith Noct",
        hp: 110,
        attack: 110,
        defense: 125,
        speed: 10,
	paldeck: "138B",
	type1: "Ground",
	type2: "Dark",
        rarity: "Legendary"
    },
    {
        species: "Anubis",
        hp: 120,
        attack: 130,
        defense: 100,
        speed: 10,
	paldeck: "139",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Desert King Anubis",
        hp: 120,
        attack: 130,
        defense: 100,
        speed: 10,
	paldeck: "139A",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Sekhmet",
        hp: 110,
        attack: 115,
        defense: 100,
        speed: 10,
	paldeck: "140",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Prixter",
        hp: 90,
        attack: 110,
        defense: 90,
        speed: 10,
	paldeck: "141",
	type1: "Ground",
	type2: "Dark",
        rarity: "Legendary"
    },
    {
        species: "Prixter Lux",
        hp: 90,
        attack: 115,
        defense: 90,
        speed: 10,
	paldeck: "141B",
	type1: "Ground",
	type2: "Electric",
        rarity: "Legendary"
    },
    {
        species: "Tetroise",
        hp: 95,
        attack: 100,
        defense: 135,
        speed: 10,
	paldeck: "142",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Tetroise Primo",
        hp: 95,
        attack: 100,
        defense: 140,
        speed: 10,
	paldeck: "142B",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Nyafia",
        hp: 110,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "143",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Mimog",
        hp: 60,
        attack: 60,
        defense: 130,
        speed: 10,
	paldeck: "144",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Xenovader",
        hp: 90,
        attack: 125,
        defense: 85,
        speed: 10,
	paldeck: "145",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Xenogard",
        hp: 110,
        attack: 120,
        defense: 130,
        speed: 10,
	paldeck: "146",
	type1: "Dragon",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Prunelia",
        hp: 105,
        attack: 95,
        defense: 100,
        speed: 10,
	paldeck: "147",
	type1: "Grass",
	type2: "Dark",
        rarity: "Legendary"
    },
    {
        species: "Nitemary",
        hp: 105,
        attack: 95,
        defense: 105,
        speed: 10,
	paldeck: "148",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Nitemary Botan",
        hp: 110,
        attack: 95,
        defense: 105,
        speed: 10,
	paldeck: "148B",
	type1: "Grass",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Smokie",
        hp: 85,
        attack: 90,
        defense: 85,
        speed: 10,
	paldeck: "149",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Smokie Cryst",
        hp: 85,
        attack: 90,
        defense: 90,
        speed: 10,
	paldeck: "149B",
	type1: "Dark",
	type2: "Ice",
        rarity: "Legendary"
    },
    {
        species: "Omascul",
        hp: 95,
        attack: 105,
        defense: 100,
        speed: 10,
	paldeck: "150",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Whalaska",
        hp: 105,
        attack: 115,
        defense: 110,
        speed: 10,
	paldeck: "151",
	type1: "Ice",
	type2: "Water",
        rarity: "Legendary"
    },
    {
        species: "Whalaska Ignis",
        hp: 105,
        attack: 120,
        defense: 110,
        speed: 10,
	paldeck: "151B",
	type1: "Ice",
	type2: "Fire",
        rarity: "Legendary"
    },
    {
        species: "Verdash",
        hp: 90,
        attack: 115,
        defense: 90,
        speed: 10,
	paldeck: "152",
	type1: "Grass",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Splatterina",
        hp:95,
        attack: 115,
        defense: 105,
        speed: 10,
	paldeck: "153",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Gildane",
        hp: 120,
        attack: 110,
        defense: 110,
        speed: 10,
	paldeck: "154",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Dogen",
        hp: 90,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "155",
	type1: "Neutral",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Bulldosu",
        hp: 115,
        attack:95,
        defense: 100,
        speed: 10,
	paldeck: "156",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Celesdir",
        hp: 120,
        attack: 110,
        defense: 100,
        speed: 10,
	paldeck: "157",
	type1: "Neutral",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Celesdir Noct",
        hp: 120,
        attack: 115,
        defense: 100,
        speed: 10,
	paldeck: "157B",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Astegon",
        hp: 100,
        attack: 125,
        defense: 125,
        speed: 10,
	paldeck: "158",
	type1: "Dragon",
	type2: "Dark",
        rarity: "Legendary"
    },
    {
        species: "Knocklem",
        hp: 105,
        attack: 110,
        defense: 135,
        speed: 10,
	paldeck: "159",
	type1: "Ground",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Knocklem Ignis",
        hp: 105,
        attack: 115,
        defense: 135,
        speed: 10,
	paldeck: "159B",
	type1: "Fire",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Silvegis",
        hp: 120,
        attack: 110,
        defense: 115,
        speed: 10,
	paldeck: "160",
	type1: "Dragon",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Azurmane",
        hp: 130,
        attack: 120,
        defense: 110,
        speed: 10,
	paldeck: "161",
	type1: "Electric",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Valentail",
        hp: 75,
        attack: 80,
        defense: 70,
        speed: 10,
	paldeck: "162",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Snock",
        hp: 65,
        attack: 70,
        defense: 75,
        speed: 10,
	paldeck: "163",
	type1: "Electric",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Snock Terra",
        hp: 65,
        attack: 70,
        defense: 80,
        speed: 10,
	paldeck: "163B",
	type1: "Electric",
	type2: "",
        rarity: "Legendary"
    },    
    {
        species: "Souffline",
        hp: 70,
        attack: 75,
        defense: 60,
        speed: 10,
	paldeck: "164",
	type1: "Grass",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Lapiron",
        hp: 70,
        attack: 75,
        defense: 80,
        speed: 10,
	paldeck: "165",
	type1: "Ground",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Hoodle",
        hp: 70,
        attack: 85,
        defense: 80,
        speed: 10,
	paldeck: "166",
	type1: "Dark",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Slowatt",
        hp: 80,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "167",
	type1: "Electric",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Bakemi",
        hp: 70,
        attack: 85,
        defense: 80,
        speed: 10,
	paldeck: "168",
	type1: "Dark",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Solmora",
        hp: 90,
        attack: 90,
        defense: 85,
        speed: 10,
	paldeck: "169",
	type1: "Water",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Solmora Lux",
        hp: 90,
        attack: 95,
        defense: 85,
        speed: 10,
	paldeck: "169B",
	type1: "Water",
	type2: "Electric",
        rarity: "Epic"
    },
    {
        species: "Lapure",
        hp: 105,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "170",
	type1: "Neutral",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Eidrolon",
        hp: 115,
        attack: 125,
        defense: 120,
        speed: 10,
	paldeck: "171",
	type1: "Dragon",
	type2: "Dark",
        rarity: "Legendary"
    },
    {
        species: "Eidrolon Ignis",
        hp: 115,
        attack: 130,
        defense: 120,
        speed: 10,
	paldeck: "171B",
	type1: "Dragon",
	type2: "Fire",
        rarity: "Legendary"
    },
    {
        species: "Dynamoff",
        hp: 75,
        attack: 85,
        defense: 80,
        speed: 10,
	paldeck: "172",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Tropicaw",
        hp: 85,
        attack: 85,
        defense: 90,
        speed: 10,
	paldeck: "173",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Flaracle",
        hp: 110,
        attack: 125,
        defense: 105,
        speed: 10,
	paldeck: "174",
	type1: "Fire",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Ophydia",
        hp: 130,
        attack: 115,
        defense: 120,
        speed: 10,
	paldeck: "175",
	type1: "Grass",
	type2: "Water",
        rarity: "Legendary"
    },
    {
        species: "Dupin",
        hp: 100,
        attack: 110,
        defense: 100,
        speed: 10,
	paldeck: "176",
	type1: "Fire",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Roujay",
        hp: 110,
        attack: 115,
        defense: 95,
        speed: 10,
	paldeck: "177",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Venusa",
        hp: 80,
        attack: 85,
        defense: 90,
        speed: 10,
	paldeck: "178",
	type1: "Dark",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Mycora",
        hp: 105,
        attack: 95,
        defense: 90,
        speed: 10,
	paldeck: "179",
	type1: "Grass",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Loomen",
        hp: 90,
        attack: 100,
        defense: 95,
        speed: 10,
	paldeck: "180",
	type1: "Dark",
	type2: "Fire",
        rarity: "Legendary"
    },
    {
        species: "Wistella",
        hp: 80,
        attack: 90,
        defense: 60,
        speed: 10,
	paldeck: "181",
	type1: "Dark",
	type2: "",
        rarity: "Epic"
    },
    {
        species: "Solenne",
        hp: 110,
        attack: 115,
        defense: 115,
        speed: 10,
	paldeck: "182",
	type1: "Dark",
	type2: "Neutral",
        rarity: "Legendary"
    },
    {
        species: "Renjishi",
        hp: 105,
        attack: 120,
        defense: 100,
        speed: 10,
	paldeck: "183",
	type1: "Fire",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Aegidron",
        hp: 105,
        attack: 125,
        defense: 140,
        speed: 10,
	paldeck: "184",
	type1: "Dragon",
	type2: "Ground",
        rarity: "Legendary"
    },
    {
        species: "Grizzbolt",
        hp: 120,
        attack: 105,
        defense: 105,
        speed: 10,
	paldeck: "185",
	type1: "Electric",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Lyleen",
        hp: 120,
        attack: 120,
        defense: 110,
        speed: 10,
	paldeck: "186",
	type1: "Grass",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Fortune Bringer Lyleen",
        hp: 120,
        attack: 120,
        defense: 110,
        speed: 10,
	paldeck: "186A",
	type1: "Grass",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Lyleen Noct",
        hp: 115,
        attack: 120,
        defense: 115,
        speed: 10,
	paldeck: "186B",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Fortune Bringer Lyleen Noct",
        hp: 115,
        attack: 120,
        defense: 115,
        speed: 10,
	paldeck: "186B1",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "Orserk",
        hp: 120,
        attack: 130,
        defense: 115,
        speed: 10,
	paldeck: "187",
	type1: "Dragon",
	type2: "Electric",
        rarity: "Legendary"
    },
    {
        species: " Faleris",
        hp: 105,
        attack: 110,
        defense: 115,
        speed: 10,
	paldeck: "188",
	type1: "Fire",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: " Faleris Aqua",
        hp: 110,
        attack: 110,
        defense: 115,
        speed: 10,
	paldeck: "188B",
	type1: "Water",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: " Shadowbeak",
        hp: 120,
        attack: 120,
        defense: 140,
        speed: 10,
	paldeck: "189",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: "White Shadowbeak",
        hp: 120,
        attack: 120,
        defense: 140,
        speed: 10,
	paldeck: "189A",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: " Selyne",
        hp: 130,
        attack: 115,
        defense: 110,
        speed: 10,
	paldeck: "190",
	type1: "Dark",
	type2: "Neutral",
        rarity: "Legendary"
    },
    {
        species: "Bestigor",
        hp: 140,
        attack: 130,
        defense: 120,
        speed: 10,
	paldeck: "191",
	type1: "Ice",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: " Shaolong",
        hp: 140,
        attack: 135,
        defense: 120,
        speed: 10,
	paldeck: "192",
	type1: "Dragon",
	type2: "Water",
        rarity: "Legendary"
    },
    {
        species: " Silvance",
        hp: 140,
        attack: 120,
        defense: 110,
        speed: 10,
	paldeck: "193",
	type1: "Grass",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: " Dandilord",
        hp: 125,
        attack: 135,
        defense: 110,
        speed: 10,
	paldeck: "194",
	type1: "Grass",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: " Bellanoir",
        hp: 120,
        attack: 150,
        defense: 100,
        speed: 10,
	paldeck: "195",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: " Bellanoir Libero",
        hp: 120,
        attack: 150,
        defense: 100,
        speed: 10,
	paldeck: "195",
	type1: "Dark",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: " Xenolord",
        hp: 130,
        attack: 120,
        defense: 120,
        speed: 10,
	paldeck: "196",
	type1: "Dark",
	type2: "Dragon",
        rarity: "Legendary"
    },
    {
        species: " Hartalis",
        hp: 135,
        attack: 130,
        defense: 100,
        speed: 10,
	paldeck: "197",
	type1: "Neutral",
	type2: "",
        rarity: "Legendary"
    },
    {
        species: " Paladius",
        hp: 130,
        attack: 120,
        defense: 145,
        speed: 10,
	paldeck: "198",
	type1: "Dark",
	type2: "",
        rarity: "Mythical"
    },
    {
        species: " Necromus",
        hp: 130,
        attack: 145,
        defense: 120,
        speed: 10,
	paldeck: "199",
	type1: "Dark",
	type2: "",
        rarity: "Mythical"
    },
    {
        species: " Frostallion",
        hp: 140,
        attack: 140,
        defense: 120,
        speed: 10,
	paldeck: "200",
	type1: "Ice",
	type2: "",
        rarity: "Mythical"
    },
    {
        species: "Royal Frostallion",
        hp: 140,
        attack: 140,
        defense: 120,
        speed: 10,
	paldeck: "200A",
	type1: "Ice",
	type2: "",
        rarity: "Mythical"
    },
    {
        species: " Frostallion Noct",
        hp: 140,
        attack: 140,
        defense: 135,
        speed: 10,
	paldeck: "200B",
	type1: "Dark",
	type2: "",
        rarity: "Mythical"
    },
    {
        species: " Neptilius",
        hp: 105,
        attack: 145,
        defense: 125,
        speed: 10,
	paldeck: "201",
	type1: "Water",
	type2: "",
        rarity: "Mythical"
    },
    {
        species: "Jetragon ",
        hp: 115,
        attack: 140,
        defense: 120,
        speed: 10,
	paldeck: "202",
	type1: "Dragon",
	type2: "",
        rarity: "Mythical"
    },
    {
        species: "Cyber Jetragon ",
        hp: 115,
        attack: 140,
        defense: 120,
        speed: 10,
	paldeck: "202",
	type1: "Dragon",
	type2: "",
        rarity: "Mythical"
    },
    {
        species: "Panthalus ",
        hp: 180,
        attack: 120,
        defense: 200,
        speed: 10,
	paldeck: "203",
	type1: "Water",
	type2: "",
        rarity: "Mythical"
    },



];