export const monsterTemplates = [
    {
        species: "Lamball",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "001",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Cattiva ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "002",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Chikipi ",
        hp: 60,
        attack: 60,
        defense: 60,
        speed: 10,
	paldeck: "003",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Lifmunk ",
        hp: 75,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "004",
	type1: "Grass",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Fuack ",
        hp: 60,
        attack: 80,
        defense: 60,
        speed: 10,
	paldeck: "005",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Vixy ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "006",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Celaray ",
        hp: 80,
        attack: 70,
        defense: 80,
        speed: 10,
	paldeck: "007",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Cremis ",
        hp: 70,
        attack: 70,
        defense: 75,
        speed: 10,
	paldeck: "008",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Croajiro ",
        hp: 80,
        attack: 100,
        defense: 85,
        speed: 10,
	paldeck: "009",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Herbil ",
        hp: 80,
        attack: 75,
        defense: 75,
        speed: 10,
	paldeck: "010",
	type1: "Neutral",
	type2: "Grass",
        rarity: "Common"
    },
    {
        species: "Teafant ",
        hp: 70,
        attack: 60,
        defense: 70,
        speed: 10,
	paldeck: "011",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Gumoss ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "012",
	type1: "Grass",
	type2: "Ground",
        rarity: "Common"
    },
    {
        species: "Pupperai ",
        hp: 70,
        attack: 80,
        defense: 70,
        speed: 10,
	paldeck: "013",
	type1: "Ground",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Clovee ",
        hp: 80,
        attack: 65,
        defense: 65,
        speed: 10,
	paldeck: "014",
	type1: "Grass",
	type2: "Neutral",
        rarity: "Common"
    },
    {
        species: "Jolthog ",
        hp: 70,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "015",
	type1: "Electric",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Depresso ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "016",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Pengullet ",
        hp: 70,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "017",
	type1: "Water",
	type2: "Ice",
        rarity: "Common"
    },
    {
        species: "Penking ",
        hp: 95,
        attack: 95,
        defense: 95,
        speed: 10,
	paldeck: "018",
	type1: "Water",
	type2: "Ice",
        rarity: "Rare"
    },
    {
        species: "Hoocrates ",
        hp: 70,
        attack: 70,
        defense: 80,
        speed: 10,
	paldeck: "019",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Melpaca ",
        hp: 90,
        attack: 75,
        defense: 90,
        speed: 10,
	paldeck: "020",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Melpaca ",
        hp: 120,
        attack: 85,
        defense: 90,
        speed: 10,
	paldeck: "021",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Daedream ",
        hp: 70,
        attack: 75,
        defense: 60,
        speed: 10,
	paldeck: "022",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Tanzee ",
        hp: 80,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "023",
	type1: "Grass",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Nox ",
        hp: 75,
        attack: 85,
        defense: 70,
        speed: 10,
	paldeck: "024",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Flambelle ",
        hp: 60,
        attack: 70,
        defense: 80,
        speed: 10,
	paldeck: "025",
	type1: "Fire",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Rooby ",
        hp: 75,
        attack: 70,
        defense: 75,
        speed: 10,
	paldeck: "026",
	type1: "Fire",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Mau ",
        hp: 70,
        attack: 60,
        defense: 70,
        speed: 10,
	paldeck: "027",
	type1: "Dark",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Rushroar ",
        hp: 80,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "028",
	type1: "Ground",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Foxparks ",
        hp: 65,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "029",
	type1: "Fire",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Killamari ",
        hp: 60,
        attack: 60,
        defense: 70,
        speed: 10,
	paldeck: "030",
	type1: "Dark",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Fuddler ",
        hp: 65,
        attack: 80,
        defense: 50,
        speed: 10,
	paldeck: "031",
	type1: "Ground",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Eikthyrdeer ",
        hp: 95,
        attack: 80,
        defense: 80,
        speed: 10,
	paldeck: "032",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Direhowl ",
        hp: 80,
        attack: 90,
        defense: 75,
        speed: 10,
	paldeck: "033",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Caprity ",
        hp: 100,
        attack: 70,
        defense: 90,
        speed: 10,
	paldeck: "034",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Swee ",
        hp: 60,
        attack: 60,
        defense: 60,
        speed: 10,
	paldeck: "035",
	type1: "Ice",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Sweepa ",
        hp: 100,
        attack: 90,
        defense: 90,
        speed: 10,
	paldeck: "036",
	type1: "Ice",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Turtacle ",
        hp: 75,
        attack: 75,
        defense: 115,
        speed: 10,
	paldeck: "037",
	type1: "Water",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Hangyu ",
        hp: 80,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "038",
	type1: "Ground",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Woolipop ",
        hp: 70,
        attack: 70,
        defense: 90,
        speed: 10,
	paldeck: "039",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Mozzarina ",
        hp: 90,
        attack: 50,
        defense: 80,
        speed: 10,
	paldeck: "040",
	type1: "Neutral",
	type2: "",
        rarity: "Rare"
    },
    {
        species: "Azurobe ",
        hp: 110,
        attack: 100,
        defense: 100,
        speed: 10,
	paldeck: "041",
	type1: "Water",
	type2: "Dragon",
        rarity: "Epic"
    },
    {
        species: "Sparkit ",
        hp: 60,
        attack: 75,
        defense: 70,
        speed: 10,
	paldeck: "042",
	type1: "Electric",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Kelpsea ",
        hp: 70,
        attack: 70,
        defense: 70,
        speed: 10,
	paldeck: "043",
	type1: "Water",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Ribunny ",
        hp: 75,
        attack: 65,
        defense: 70,
        speed: 10,
	paldeck: "044",
	type1: "Neutral",
	type2: "",
        rarity: "Common"
    },
    {
        species: "Jelliette ",
        hp: 75,
        attack: 90,
        defense: 70,
        speed: 10,
	paldeck: "045",
	type1: "Water",
	type2: "",
        rarity: "Rare"
    },







];